### ISSUE TITLE
Crux are not taken into account

### ISSUE THREAD

**Issue by Rodama-20** [BlakeBr0/MysticalCustomization#10]
**Describe the bug**
I create a new seed needing a crux but the seed grow also without it, the excat same problem comes with modifiying existing seeds
**To Reproduce**

add or modify a seed through json files with a crux argument go to the game and the seed grow without its crux.

**Expected behavior**
without the crux the seed have to stay at stage 0 when the crux is added the seed can grow

**Screenshots / Scripts / Logs**
{
   "mysticalagriculture:dirt": {
        "crux": "minecraft:cobblestone"
    }
}

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Cucumber: 1.16.4-4.1.8
 - Mystical Agriculture: 1.16.4-4.1.5
 - Mystical Customization: 1.16.4-2.1.2

**Comment by BlakeBr0** [comment]
After a quick test everything seems to be working as intended for me. Maybe this issue got resolved at some point since MA was last updated?

**Comment by Rodama-20** [comment]
Finnally i found the source of the problem:. I made a spelling mistake on one of the modified crop and only the crux change wasn't taken into account other modifcation like name or glint were done normally.
After correcting the mistake all works fine.

As a solution is it possible to write something into the log file when an unkown seed is found during modification ?

Thank you for your help
Rodama
