### ISSUE TITLE
[1.16.5] Remove recipe

### ISSUE THREAD

**Issue by Alkasym** [BlakeBr0/MysticalCustomization#11]
Hi, 

We want to remove the seed recipe create with mystical customization to change them with KubeJS but it doesn't work.

To Reproduce, just add the following line in KubeJS server script :  
     e.remove({ id: "mysticalagriculture:alfsteel_seeds_infusion" })

---------------------------------------------------------------------------------------------------------------------------------

 - Minecraft: 1.16.5
 - Forge: 36.0.46
 - Cucumber: 4.1.8
 - Mystical Agriculture: 4.1.5
 - Mystical Customization: 2.1.2
 - KubeJS : 1605.3.6-build.172

**Comment by BlakeBr0** [comment]
Try setting the ingredient to `minecraft:air` in the json file.

**Comment by Alkasym** [comment]
Thanks you that works fine :)
