### ISSUE TITLE
more textures please

### ISSUE THREAD

**Issue by Warbringer12** [BlakeBr0/MysticalCustomization#12]
the ability to use more crop textures and essence textures.
like adding some of the essence textures that are inside of mystical agriculture
example: enderman essence, blitz essence, prismarine essence, slime essence, mystical flower, apatite essence

**Comment by BlakeBr0** [comment]
You can use any texture you want, as the config is just a texture location from a resource pack. The textures listed in the docs are just files from the Mystical Agriculture resources: [see here](https://github.com/BlakeBr0/MysticalAgriculture/tree/1.16/src/main/resources/assets/mysticalagriculture/textures/item). You should be able to use any of those if you want to.

With that said, I'll look into adding more of the grayscale textures like I have listed in the docs in the future.

**Comment by BlakeBr0** [comment]
I think I added 1 more grayscale essence texture in 4.2.0. I think the ones in there are fine for now, but I'll try to keep adding new ones as I see fit.
