### ISSUE TITLE
Attempting to create crops for Prudentium, Tertium, Imperium, and Supremium Essences will crash the game on boot

### ISSUE THREAD

**Issue by Isshiro** [BlakeBr0/MysticalCustomization#13]
**Description**
Attempting to create custom crops for T2-T5 Essences will crash the game on boot; I suspect it's caused when Customization tries to create a new mysticalagriculture:tier_essence, but sees that one already exists and just doesn't know what to do.

Worth mentioning as well; crops for Insanium and Creative essences have produced no issues, likely due to them being Agradditions items, instead of Agriculture ones.

**To Reproduce**
1. Add T2-T5 crops using Customization's configs
2. Attempt to launch the game

**Expected behavior**
Expected behaviour is that MC will create seeds for the essences, similar to what already exists for Inferium.

**Screenshots / Scripts / Logs**
Included are 5 crash reports; while I doubt there is much variation between them, it might provide some insight.
Also attached the jsons I used for the crops.
[Crops.zip](https://github.com/BlakeBr0/MysticalCustomization/files/6254714/Crops.zip)
[Crash_Reports.zip](https://github.com/BlakeBr0/MysticalCustomization/files/6254717/Crash_Reports.zip)

**Versions**
 - Minecraft: 1.16.5
 - Forge: 36.1.2
 - Cucumber: 4.1.9
 - Mystical Agriculture: 4.1.7
 - Mystical Customization: 2.1.3

**Comment by BlakeBr0** [comment]
Even though I despise the idea of 'supremium seeds', I guess I'll add a special case for this.
