### ISSUE TITLE
Will Mystical Customization be backported to 1.12.2 [Or something similar]?

### ISSUE THREAD

**Issue by Handeril** [BlakeBr0/MysticalCustomization#16]
I'm aware you've made it clear that feature requests will only be added to the latest supported Minecraft version, and honestly, 1.12.2 is honestly pretty far from "current", at this point.

**Is your feature request related to a problem? Please describe.**
In short, I'm looking for a way to not only make custom seeds [while still being compatible with Agricraft], but also add new Mystical Agriculture seed tiers [if possible] in Minecraft 1.12.2.

If you decide to do a backport to 1.12.2, I'd recommend it being a "one time" thing unless it's a VERY serious problem that requires a singular update to fix it.

**_I will note here that I acknowledge that this is your own decision, and I will have to respect what your decision is either way._**

**Describe the solution you'd like**
The main things I'm requesting is that the backport have the current features of the most recent version [when it was made], and for it to please be compatible with Agricraft [avoiding a "Already Constructing Vertexes" crash], and possibly Immersive Engineering [if you want to].

**Describe alternatives you've considered**
I have tried Mystical Creations, I'm very aware that mod exists. However, Focamacho has stated [here](https://github.com/Focamacho/MysticalCreations/issues/6) that they don't have the time to make an update to their mod. In the same thread, I did note that I was thankful for the fix they provided for the Vertex Error, which worked for a while since I was just messing around with mod-compatibility. However, as I also mentioned in that thread, I would start working on a modpack sometime this summer [which I am as of this moment].

**Additional context**
I would like to put out there I'm not trying to be "that impatient guy" or push for anything you don't want to do, I respect your decision either way on this matter.

I would also like to put out there that this doesn't have to be a "one way street" for a solution, if you want to help Mystical Creations make an update, via a fork and pull request situation, it's up to you.

I apologize in advance if I wasted your time with this issue report, wanted to see if you could help.

**Comment by BlakeBr0** [comment]
It wouldn't be possible to backport this mod because the entire thing is based on changes made in the 1.13+ rewrite. I would have to make a new one from scratch, and use a bunch of hacks, which I don't think is worth it.
