### ISSUE TITLE
model and item textures for custom crop and essence missing

### ISSUE THREAD

**Issue by justin9106** [BlakeBr0/MysticalCustomization#18]
**Describe the bug**
 model and item textures are missing in jei and the output log gives this error/warning: java.io.FileNotFoundException
 entire output log in pastebin: https://pastebin.com/disdcnzJ
 my custom seed code in pastebin: https://pastebin.com/90KKEWJ5

**To Reproduce**
 create a custom seed with flower, essence, and seed textures (I may have done somthing wrong in the code and don't realize it)
**Expected behavior**
to have the textures loaded properly

**Screenshots / Scripts / Logs**
code screenshot:
![Screenshot 2021-08-26 162328](https://user-images.githubusercontent.com/74918531/131038008-54f2c106-22bf-4158-8bb3-c98b24d04dd1.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.21
 - Mystical Customization: 2.15

**Comment by justin9106** [comment]
it seems having the "ingredient" line made it work

**Comment by BlakeBr0** [comment]
For future reference if anyone sees this: the essence texture location had `block` instead of `item`.
