### ISSUE TITLE
Can't change crop recipes

### ISSUE THREAD

**Issue by BestMod** [BlakeBr0/MysticalCustomization#19]
**Describe the bug**
I can't change crops to use singularities instead of the base item, that or my brackets and whatnot are wrong

**To Reproduce**

https://pastebin.com/6xXTvpfH
use this code in configure_crops.json

**Expected behavior**
It *should* replace the items used for crafting the seeds with their respective singularities.

**Screenshots / Scripts / Logs**
https://imgur.com/a/a9zN8pm
^^ example
https://pastebin.com/6xXTvpfH
^^ code

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.25
 - Cucumber: 4.1.9
 - Mystical Agriculture: 4.1.8
 - Mystical Customization: 2.1.4

**Comment by BlakeBr0** [comment]
Not sure if you found the solution already, but you have an invalid json file. Make sure to use something like https://jsonlint.com/ to ensure you are using proper syntax.
