### ISSUE TITLE
How can I disable crux?

### ISSUE THREAD

**Issue by atomic-lock** [BlakeBr0/MysticalCustomization#21]
I tried many ways of disabling crux i.e
```json
"mysticalagradditions:nether_star":
{
      "crux": "none"
}
```
```json
"mysticalagradditions:nether_star":
{
      "crux": false
}
```
```json
"mysticalagradditions:nether_star":
{
      "crux": null
}
```
Please help me, I have been trying to figure this out, I am almost going to try `minecraft:air`

**Comment by BlakeBr0** [comment]
The next release will allow this by setting the crux to `null`. You will also need to update to the latest version of Mystical Agradditions.
