### ISSUE TITLE
adding crops not working for me

### ISSUE THREAD

**Issue by stomjigg** [BlakeBr0/MysticalCustomization#22]
{
    "type": "ressource",
    "tier": "mysticalagriculture:1",
    "ingredient": {
        "item": "mysticalagriculture:prosperity_shard"
    },
    "color": {
        "flower": "eeeeee",
        "essences": "eeeeee",
        "seeds": "eeeeee"
    },
    "textures": {
        "flower": "mysticalagriculture:block/flower_dust",
        "essence": "mysticalagriculture:item/essence_flame",
        "seeds": "mysticalagriculture:item/mystical_seeds"
    }
}

file named prosperity.json, tried prosperity_seed.json to

did this and no seeds appear in JEI

i tried for prosperity shard, allthemodium, vibranium, and unobtainium, nothing work ( modpack all the mod 7 version 0.2.13 )

 - Minecraft: 1.18.1
 - Forge: 39.0.9
 - Cucumber: 5.0.1
 - Mystical Agriculture: 5.0.1
 - Mystical Agradditions: 5.0.2
 - Mystical Customization: 3.0.0

**Comment by 1TruGod** [comment]
You have resources spelt as ressources, with an extra s. But I do concur that even if that were fixed, i don't think mystical customization is working.

I tried adding the crops.zip from this past thread and the seeds do not appear anywhere. https://github.com/BlakeBr0/MysticalCustomization/issues/13

Note this issue is only in 1.18, when I added those files from crops.zip into 1.16.5 it worked fine

**Comment by Raidobw2** [comment]
Hey, about that and for the people coming across this issue, it looks like that was changed in 1.18. And honestly, the change is totally reasonable and even more friendly for modders :) the docs just need a small touch to correct something in the Types.
In short, check his site https://blakesmods.com/docs/mysticalcustomization/adding-crops#type.
Specifically, the `/mysticalcustomization types` command for in-game. Run that, and here's the result:
![image](https://user-images.githubusercontent.com/17010632/150341485-4086cb4b-0912-49d7-9701-a0677355889f.png)
It now uses resource location.
`mysticalagriculture:resource`
`mysticalagriculture:mob`
For example, that's how you would write that change for a specific seed:
![image](https://user-images.githubusercontent.com/17010632/150341401-1faad7ef-70db-467c-8638-5ea256029b55.png)
And the result in-game:
![image](https://user-images.githubusercontent.com/17010632/150341547-7298c7cf-4e92-4179-80cc-0eddcab288a5.png)
Cheers

**Comment by 1TruGod** [comment]
> Hey, about that and for the people coming across this issue, it looks like that was changed in 1.18. And honestly, the change is totally reasonable and even more friendly for modders :) the docs just need a small touch to correct something in the Types. In short, check his site https://blakesmods.com/docs/mysticalcustomization/adding-crops#type. Specifically, the `/mysticalcustomization types` command for in-game. Run that, and here's the result: ![image](https://user-images.githubusercontent.com/17010632/150341485-4086cb4b-0912-49d7-9701-a0677355889f.png) It now uses resource location. `mysticalagriculture:resource` `mysticalagriculture:mob` For example, that's how you would write that change for a specific seed: ![image](https://user-images.githubusercontent.com/17010632/150341401-1faad7ef-70db-467c-8638-5ea256029b55.png) And the result in-game: ![image](https://user-images.githubusercontent.com/17010632/150341547-7298c7cf-4e92-4179-80cc-0eddcab288a5.png) Cheers

Thank you so much for this. Solves everything!

**Comment by BlakeBr0** [comment]
I've updated the docs to mention this change.

**Comment by Raidobw2** [comment]
Much thanks! Have a good day!

**Comment by madacrex** [comment]
@Raidobw2 u have ds to talk about this? Or u can help me with my issue? Its right now open
