### ISSUE TITLE
Port to 1.12.2

### ISSUE THREAD

**Issue by BraveCaperCat** [BlakeBr0/MysticalCustomization#23]
**Describe the solution you'd like**
Port to 1.12.2 (Support 1.12.2)

**Describe alternatives you've considered**
Other mod that does the same thing for 1.12.2
**Additional context**
N/A

**Comment by BlakeBr0** [comment]
See #16

**Comment by BraveCaperCat** [comment]
> See #16

I don't look in closed issues, that's why i did make a duplicate :(
