### ISSUE TITLE
the whole mod doesnt seem to be working

### ISSUE THREAD

**Issue by Dycku** [BlakeBr0/MysticalCustomization#25]
well no matter what i code it just doesnt seem to be working, i even used the example code to see if it works, i also did this for the tiers, that also didnt work

i used the example code from the website and changed the items independently. 
it is not showing up in jei or anything, the mysticalcustomization command also doesnt show the added tier
{
    "name": "Test",
    "type": "resource",
    "tier": "mysticalagriculture:1",
    "ingredient": {
      "item": "extendedcrafting:crystaltine_ingot"
    },
    "color": {
        "flower":"eb7a34",
        "essences":"eb7a34",
        "seeds":"eb7a34"
    },
    "textures": {
      "flower": "mysticalagriculture:block/flower_dust",
      "essence": "mysticalagriculture:item/essence_dust"
    }
  }

also tried the mysticalagriculture:resource
also tried independed colours to see if that changes anything

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6
 - Mystical Customization: 2.1.7
![image](https://user-images.githubusercontent.com/103742051/169712676-b1981619-ee7b-4aa6-ab2c-1c6a512e0f13.png)
or i might just be really stupid

**Comment by Dycku** [comment]
reinstalled the mod, seems to be working

**Comment by madacrex** [comment]
@Dycku U have ds or something? I need help to make a custom seed
