### ISSUE TITLE
Can't use mysticalagradditions:6 tier when creating a new crop

### ISSUE THREAD

**Issue by Nevrai** [BlakeBr0/MysticalCustomization#27]
### Describe the bug

I’ve tried to create custom seeds, but it’s not working. I’ve also tried including the parameters that weren’t necessary, but it still doesn’t work. No seeds are being loaded by Mystical Customization.

```
{
  "name": "Cyanite",
  "type": "mysticalagriculture:resource",
  "tier": "mysticalagriculture:4",
  "color": "32a8a8",
  "ingredient": {
    "tag": "forge:ingots/cyanite"
  },
  "textures": {
    "flower": "mysticalagriculture:block/flower_ingot",
    "essence": "mysticalagriculture:item/essence_ingot",
    "seeds": "mysticalagriculture:item/mystical_seeds"
  },
  "enabled": true
}
```

### Versions

 * **Minecraft:** 1.18.2
 * **Forge:** 40.1.80
 * **Mystical Customization:** 3.1.2 (latest)
 * **Mystical Agriculture:** 5.1.2 (latest)
 * **Cucumber Library:** 5.1.3 (latest)

**Comment by BlakeBr0** [comment]
Are there any errors in the logs? Is the file in the correct folder?

**Comment by Nevrai** [comment]
@BlakeBr0 I figured out the issue with the cyanite seeds: Mystical Agriculture already has cyanite seeds. So now, I just added recipes for them and enabled them in JEI.

However, with my other seeds, which are using Agradditions’ tier 6, they are not working. I’m getting this error:
`com.google.gson.JsonSyntaxException: Invalid crop tier provided: mysticalagradditions:6`

This seems like a bug, as I made sure to use proper spelling and syntax, as well as check the in-game `/mysticalcustomization tiers` command, yet it’s not recognizing that tier 6 exists.

Here is the JSON file:
```json
{
  "type": "mysticalagriculture:resource",
  "tier": "mysticalagradditions:6",
  "color": "501075",
  "ingredient": {
    "tag": "forge:gems/void"
  }
}
```

The file is in the correct location (`config\mysticalcustomization\crops`).
[Here’s the full error from latest.log.](https://pastebin.com/raw/eyTgrJdj)

**Comment by BlakeBr0** [comment]
If you were to set it to one of the default tiers then update it to tier 6 in the update file, does that work? Maybe it's a load order issue?

**Comment by Nevrai** [comment]
Yes, that worked! Wonderful. Thanks for the tip.

Hopefully you can figure out what was causing this, though.

**Comment by BlakeBr0** [comment]
Fixed by ce35f444851e9bf167017dab213da98502e5ba87

**Comment by Nevrai** [comment]
Thank you for the fix. Could this be backported to 1.18.2? Would be wonderful

**Comment by BlakeBr0** [comment]
If I do another release for 1.18 I'll be sure to add this fix in.
