### ISSUE TITLE
1.18.2 How put kubejs custom items in ingredients

### ISSUE THREAD

**Issue by RapidMesck** [BlakeBr0/MysticalCustomization#30]
**Describe the bug**
the recipe cannot identify a custom item from kubejs

**Screenshots / Scripts / Logs**

```
{
    "name": "Elemental Rune",
    "type": "mysticalagriculture:resource",
    "tier": "mysticalagriculture:2",
    "ingredient": {
      "tag": "kubejs:elemental_agglomeratio"
    },
    "color": "fee4ab",
    "textures": {
      "flower": "mysticalagriculture:block/flower_rock",
      "essence": "mysticalagriculture:item/essence_rock"
    }
  }
```

![image](https://user-images.githubusercontent.com/44342800/224558971-36b5c3fb-540b-495f-b672-0b046628d21a.png)
![image](https://user-images.githubusercontent.com/44342800/224559065-4449146b-c1b4-4560-8104-bb8785eeed11.png)

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.2.0
 - Cucumber: Cucumber-1.18.2-5.1.3
 - Mystical Agriculture: MysticalAgriculture-1.18.2-5.1.4
 - Mystical Customization: MysticalCustomization-1.18.2-3.1.2

**Comment by RapidMesck** [comment]
I used this solution:

i made a custom recipe using kubejs in infuser altar for seed

exemple code: 

```
let mysticalAltar = (e, output, middleItem, ingredientList) => {
		e.custom({
			type: 'mysticalagriculture:infusion',
			input: { item: middleItem },
			ingredients: ingredientList.map(item => (item.charAt(0) === '#') ? { tag: item.substring(1) } : { item: item }),
			result: { item: output }
		}).id(`kubejs:infusion_altar_crafting/${output.replace(':', '/')}`);
	};
	
onEvent('recipes', event => {

 mysticalAltar(event, 'mysticalagriculture:elemental_rune_seeds', 'mysticalagriculture:prosperity_seed_base',['mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'kubejs:elemental_agglomeratio', 'kubejs:elemental_agglomeratio', 'kubejs:elemental_agglomeratio', 'kubejs:elemental_agglomeratio'])

})
```

![image](https://user-images.githubusercontent.com/44342800/224561820-53cdd849-a829-45df-a3ed-bc1187b492bd.png)

Versions:

Minecraft: 1.18.2
Forge: 40.2.0
Cucumber: Cucumber-1.18.2-5.1.3
Mystical Agriculture: MysticalAgriculture-1.18.2-5.1.4
Mystical Customization: MysticalCustomization-1.18.2-3.1.2
Kubejs: kubejs-forge-1802.5.5-build.569

**Comment by BlakeBr0** [comment]
Did you mean to use a tag in the first example? You seem to be using an item id in the second example.

**Comment by RapidMesck** [comment]
Sorry, in the seed code it was the variable "tag" and not the variable "item", now it's working normally

Code fixed:

```
{
    "name": "Elemental Rune",
    "type": "mysticalagriculture:resource",
    "tier": "mysticalagriculture:3",
    "ingredient": {
      "item": "kubejs:elemental_agglomeratio"
    },
    "color": "fee4ab",
    "textures": {
      "flower": "mysticalagriculture:block/flower_rock",
      "essence": "mysticalagriculture:item/essence_rock"
    }
  }
```

**Comment by RapidMesck** [comment]
I updated the code in the ingredient variable part and it worked

```
{
  (Code...)

  "ingredient": {
    "item": "kubejs:elemental_agglomeratio"
  }
}
```
