### ISSUE TITLE
Attempting to Edit Recipes in 1.18.2 (Forge 40.2.0)

### ISSUE THREAD

**Issue by FocusedVex** [BlakeBr0/MysticalCustomization#31]
**_EDIT: I appear to have resolved much of this. However I am still having issues with the Inferium Seed not updating to take Inferium Blocks instead of Essence._**

I am currently looking to make some of the seeds harder to craft by changing the recipes from using single ingots/gems/etc to using the block of the item and by using Essence Blocks instead of single essences. For example using Iron Blocks instead of using Iron Ingots for the iron seed.

I have successfully changed the Tier Options to use Blocks of Essence instead of singular essence, but am running into issues with changing from using single ingots/gems to using their subsequent blocks. This also includes changing the recipe for the Inferium Seed to use Inferium Blocks instead of Essence.

Bellow is the JSON file I have started that doesn't currently work and I'm not particularly sure why. Any help would be greatly appreciated. Once I have managed to get these to work, I will likely be expanding it across a number of other crops, such as Copper, Iron, Diamond, etc.

{
  "mysticalagriculture:inferium": {
   "ingredient": {
    "item": "mysticalagriculture:inferium_block"
    },
  },
}

**Comment by madacrex** [comment]
@FocusedVex U have ds or something? I need help for make a custom seed
