### ISSUE TITLE
I wanna make a custom crop, but idk why not working :(

### ISSUE THREAD

**Issue by madacrex** [BlakeBr0/MysticalCustomization#34]
I wanna make a prosperity shard crop but i have a problem and idk which, i need help pls i dont know much of code 😭😭😭

i am argentinian and my english is a little poor :(

i have this in configure-crops:
{
"mysticalagriculture:prosperity_shard_crop": {
"name": "Prosperity Shard Crop",
"tier": "mysticalagriculture:5",
"type": "mysticalagriculture:resource",
"ingredient": {
"item": "mysticalagriculture:prosperity_shard"
},
"crux": "null"
},
"enabled": true
}

----------------------------------------------------------

and i have this in crops:
{
"type": "mysticalagriculture:resource",
"tier": "mysticalagriculture:5",
"ingredient": {
"item": "mysticalagriculture:prosperity_shard"
},
"color": {
"flower": "eeeeee",
"essences": "eeeeee",
"seeds": "eeeeee"
},
"textures": {
"flower": "mysticalagriculture:block/flower_dust",
"essence": "mysticalagriculture:item/essence_flame",
"seeds": "mysticalagriculture:item/mystical_seeds"
},
"enabled":true
}

i wanna make a prosperity shard crop tier 5 for endgame for not to go to the mine, if anyone have one crop functional pls share with me .

Versions:

Minecraft: 1.19.2
Forge: 43.2.0
Cucumber: 6.0.6
Mystical Agriculture: 6.0.8
Mystical Customization: 4.0.1

**Comment by madacrex** [comment]
@BlakeBr0 pls i need help :(

**Comment by BlakeBr0** [comment]
The `configure-crops.json` file is for editing pre-existing crops. If you're just adding your new crop you shouldn't need to put anything in there.

**Comment by madacrex** [comment]
after put the files in the folder mysticalcustomization and not work :(

**Comment by madacrex** [comment]
but the code is fine?

**Comment by BlakeBr0** [comment]
"color" should be "colors"
