### ISSUE TITLE
how to add a mob seed when i have created a mob soul type?

### ISSUE THREAD

**Issue by hyygybs** [BlakeBr0/MysticalCustomization#35]
i have created the mob soul, then what should i do next?
i think the crop type is mob, biu ingredient is what?
i tried use mysticalagriculture:soul_jar{Souls:6.0d,Type:"mysticalcustomization:phantom"}, but failed to add it.
`{
    "name": "Phantom",
    "type": "mysticalagriculture:mob",
    "tier": "mysticalagriculture:3",
    "ingredient": {
      "item": "mysticalagriculture:soul_jar{Souls:6.0d,Type:"mysticalcustomization:phantom"}"
    },
    "color": "A79985",
    "textures": {
      "flower": "mysticalagriculture:block/flower_ingot",
      "essence": "mysticalagriculture:item/essence_ingot"
    }
}`
here are the mob soul i have created:
`{
  "name": "Phantom",
  "souls": 6.0,
  "entities": [
    "minecraft:phantom"
  ],
  "color": "A79985"
}`

**Comment by BlakeBr0** [comment]
The ingredient should look something like this:

```
    {
      "type": "forge:partial_nbt",
      "item": "mysticalagriculture:soul_jar",
      "nbt": {
        "Type": "mysticalagriculture:pig",
        "Souls": 8.0
      }
    },
```

Copied from https://github.com/BlakeBr0/MysticalAgriculture/blob/1.19.4/src/main/resources/data/mysticalagriculture/recipes/passive_soulium_dagger.json
