### ISSUE TITLE
(1.16.5) I can't get adding crops to work

### ISSUE THREAD

**Issue by pinky12022** [BlakeBr0/MysticalCustomization#36]
Mod version: 2.1.7
Minecraft version: 1.16.5

I am trying to add a crop for Druidcraft's fiery glass, and it just won't work. I'm not sure what I'm doing wrong.

I named the file "fiery_glass_seeds.json" and here's what I have:

{
  "name": "Fiery Glass Seeds",
  "type": "resource",
  "tier": "mysticalagriculture:1",
  "ingredient": {
    "item": "druidcraft:fiery_glass"
  },
  "color": "FFA500",
  "textures": {
    "flower": "mysticalagriculture:block/flower_rock",
    "essence": "mysticalagriculture:item/essence_flame"
    "seeds": "mysticalagriculture:item/mystical_seeds"
  },
  "crux": "minecraft:dirt"
}

Why won't it work?

**Comment by BlakeBr0** [comment]
Did you check the logs for errors

**Comment by pinky12022** [comment]
> Did you check the logs for errors

How do I do that? I'm new to modding sorry

**Comment by BlakeBr0** [comment]
In your instance folder there should be a `logs` folder with a `latest.log` file

**Comment by pinky12022** [comment]
> In your instance folder there should be a `logs` folder with a `latest.log` file

Alright, I looked but I can't make heads or tails of it

**Comment by BlakeBr0** [comment]
`"essence": "mysticalagriculture:item/essence_flame"` this line is missing a comma.
