### ISSUE TITLE
Disabling more than one augment

### ISSUE THREAD

**Issue by TF541Productions** [BlakeBr0/MysticalCustomization#37]
Hello!
I'm having an issue regarding editing the base mod's augments in the `"configure-aguments.json"` file.

I was able to use the example file in the documentation to disabled Mining AOE 1 using:
```
{
  "mysticalagriculture:mining_aoe_i": {
    "enabled": false
  }
}
```
However, I cannot figure out a way to write other augments in the .json file to disable them. I've tried adding them in the first bracket:
```
{
  "mysticalagriculture:mining_aoe_i": {
    "enabled": false
  }
  "mysticalagriculture:flight": {
    "enabled": false
  }
}
```
I've tried separate brackets...
```
{
  "mysticalagriculture:mining_aoe_i": {
    "enabled": false
  }
}
{
  "mysticalagriculture:flight": {
    "enabled": false
  }
}
```
But sadly to no avail, in fact it reenables Mining AOE if I try adding anything additional.
So, any help with this would be greatly appreciated!

**Comment by BlakeBr0** [comment]
https://jsonlint.com/
