### ISSUE TITLE
1.20.1 custom crops no work

### ISSUE THREAD

**Issue by hallool** [BlakeBr0/MysticalCustomization#38]
**Describe the bug**
i cant create a custom crop/seed

**To Reproduce**
i placed the .json file in config\mysticalcustomization\crops

**Expected behavior**
to see new crops in jei or with mc commands

**Screenshots / Scripts / Logs**
[Salt.txt](https://github.com/BlakeBr0/MysticalCustomization/files/12148753/Salt.txt)

![grafik](https://github.com/BlakeBr0/MysticalCustomization/assets/48066058/11e48347-42f6-411f-b585-081191ccc657)

![grafik](https://github.com/BlakeBr0/MysticalCustomization/assets/48066058/b0ca548c-be2c-4b6f-883b-0b2692781e17)

but this one works i dont get it.. 
[imperium.txt](https://github.com/BlakeBr0/MysticalCustomization/files/12148775/imperium.txt)

**Versions
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber:7.0.0
 - Mystical Agriculture: 7.0.1
 - Mystical Customization: 5.0.0

**Comment by BlakeBr0** [comment]
Are there errors in the logs? If the file name has a capital S it won't work (needs to be all lowercase and have underscores in place of spaces)

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
