### ISSUE TITLE
New seeds do not have any recipes.                    The problem is not displayed in the latest.logs

### ISSUE THREAD

**Issue by Sorinstratu** [BlakeBr0/MysticalCustomization#40]
- Minecraft:1.20.1
 - Forge:47.1.47
 - Cucumber:7.0.1
 - Mystical Agriculture:7.0.3
 - Mystical Customization:5.0.0

**Comment by BlakeBr0** [comment]
Can you post your crop json? If you set an ingredient it should have an Infusion crafting recipe to make it.

**Comment by Sorinstratu** [comment]
{
  "name": "Arlemite",
  "type": "mysticalagriculture:resource",
  "tier": "mysticalagriculture:4",
  "ingredient": {
    "tag": "forge:ingots/arlemite"
  },
  "color": "9DD75A",
  "textures": {
    "flower": "mysticalagriculture:block/flower_ingot",
    "essence": "mysticalagriculture:item/essence_ingot", 
"seeds": "mysticalagriculture:item/mystical_seeds"
  }
}

**Comment by BlakeBr0** [comment]
Does it work if you just use an item instead of a tag?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
