### ISSUE TITLE
Custom texture doesn't create models files

### ISSUE THREAD

**Issue by MLDEG** [BlakeBr0/MysticalCustomization#41]
**Describe the bug**
Creating a new seed with custom textures doesn't create the models json to display the textures, while applying a color to the base texture works.

**To Reproduce**
In the json file "mysticalcustomization/crops" remove the "color" line and add the "seeds" line to "textures" and put the path of the custom textures (e.g. "kubejs:item/aquite_essence")

**Expected behavior**
Show textures ingame with custom textures applied

**Screenshots / Scripts / Logs**
Logs:
https://pastebin.com/xq7R2ABc

![2023-09-14_11 21 42](https://github.com/BlakeBr0/MysticalCustomization/assets/90324978/ca8ebb0c-82e9-43fe-b55f-e94346741dbb)

This is my json file for an Aquite seed
https://pastebin.com/ZDRDr0pp

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.47
 - Cucumber: 1.20.1-7.0.1
 - Mystical Agriculture: 1.20.1-7.0.3
 - Mystical Customization: 1.20.1-5.0.0
 
Thank you for your work !

**Comment by BlakeBr0** [comment]
I somewhat unintentionally removed the automatic model generation in 1.20. I'll see if I can re-add that in some form if it doesn't cause issues. 

In the mean time you could probably add those files to your resource pack manually. I'm not sure how it would work using kubejs. Theoretically, you could add the models to a resource pack in the `mysticalagriculture` namespace corresponding to the generated block/items in game and they should load like normal.

**Comment by MLDEG** [comment]
I was hesitant to add them manually in the first place, so I'm going to add them while waiting for an update that will potentially fix the problem.

Thank you =)

**Comment by BlakeBr0** [comment]
I looked into re-adding this earlier and figured out why I removed this functionality in the first place. In 1.19.3 Mojang changed a ton of the internals for model loading which made it so my method of dynamically generating them didn't work anymore. 

I think what I'll do is add documentation for this use case since doing it dynamically is significantly more difficult now.

**Comment by BlakeBr0** [comment]
I added a section to the docs with examples: https://blakesmods.com/docs/mysticalcustomization/adding-crops#custom-models
