### ISSUE TITLE
Can't add new recipie 

### ISSUE THREAD

**Issue by Oatise** [BlakeBr0/MysticalCustomization#43]
**Describe the bug**
Trying to edit Titanium Seeds to work with chaosawawakens, I've done ruby no problem but can't add this

**Expected behavior**
To add new titanium to recipie & edit tier

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalCustomization/assets/136215926/ce717437-fd27-42c8-a80c-26395db65995)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.39
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6
 - Mystical Customization: 2.1.7

**Comment by BlakeBr0** [comment]
Your "recipies" field is at the top level so it won't work. It's also spelt wrong, and not even needed because the default for each recipe is true. That field also doesn't exist for versions of Customization prior to 3.1.2.

If just changing the ingredient doesn't work you may have to edit the recipes manually using something like CraftTweaker. If you're trying to change the essence recipe you can change that in cucumber-tags.json since I believe the titanium seed uses that for it's essence recipe.

**Comment by Oatise** [comment]
I am trying to edit the tier of Titanium from 4 to 6 & Have it so when I want to craft titanium seeds it uses chaosawakens' titanium nuggets. Ruby worked with no problem & under the cucumber its "null" for ruby and works fine so I am very confused on that. I do have CraftTweaker and used that to craft the ruby from the essence. Could I have an example to do so with Infusion?

I've tried a couple of things. 
1. I did use that cucumber.json file to add titanium nuggets to the list and it did work to have the nuggets be crafted
2. Switching the recipes around in the configure-crops.json makes the ruby crafting not work and revert back to tier 4 & the titanium doesn't change by swapping either
I have simplified it down to this knowing that the recipe is true by default
![image](https://github.com/BlakeBr0/MysticalCustomization/assets/136215926/c18252d7-adfe-4d3c-a105-e4bd221980f1)

and here is the swapped versions of the two
![image](https://github.com/BlakeBr0/MysticalCustomization/assets/136215926/c8c27e0b-bc19-4bcc-9b78-b52a669f632e)

**Comment by BlakeBr0** [comment]
As a note the 1.16 versions of my mods are EOL. Maybe changing ingredients didn't work in 1.16, I don't really remember. Are there any errors in the logs?

The docs for adding infusion recipes are on the wiki: https://blakesmods.com/docs/mysticalagriculture/infusion-recipes

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
