### ISSUE TITLE
Crop wont grow

### ISSUE THREAD

**Issue by Soarder** [BlakeBr0/MysticalCustomization#44]
**Describe the bug**
I can get the crop to show up, seeds essence and all, it just doesnt grow, the only recipe is in the seed reprocessor 

{
    "name": "Chromatic Iron",
    "type": "mysticalagriculture:resource",
    "tier": "mysticalagriculture:3",
    "ingredient": {
       "item": "the_vault:chromatic_iron_ingot"
  },
    "color": "eb7a34",
    "textures": {
        "flower": "mysticalagriculture:block/flower_dust",
        "essence": "mysticalagriculture:item/essence_dust",
        "seeds": "mysticalagriculture:item/mystical_seeds"
    }
}

its named chromatic_iron_seed.json

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.2.9
 - Cucumber: 5.1.3
 - Mystical Agriculture: 5.1.5
 - Mystical Customization: 3.1.2
 - Singleplayer or Multiplayer: Single
 
Thanks

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing? I just tested in the Vault Hunters modpack and everything seemed to be working for me.

If you're still experiencing this issue can you mention what exactly you're doing? I tried growing the crop with a Supremium Watering Can.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
