### ISSUE TITLE
[1.19.2] Custom seeds don't have recipes

### ISSUE THREAD

**Issue by CraftSpider** [BlakeBr0/MysticalCustomization#45]
**Describe the bug**
I'm trying to create custom seeds for a modpack I'm working on, however, only one of the seeds I've created thus far has a recipe. All others create a seed with no infusion recipe. There is no message in the logs of any failures or even warnings related to recipes.

**To Reproduce**
I have several reproducers, using both tags and items. This is an example of one such file:
```json
{
    "name": "Rich Slag",
    "type": "mysticalagriculture:resource",
    "tier": "mysticalagriculture:4",
    "ingredient": {
        "item": "thermal:rich_slag"
    },
    "color": "a25a3f",
    "textures": {
        "flower": "mysticalagriculture:block/flower_rock",
        "essence": "mysticalagriculture:item/essence_rock",
        "seeds": "mysticalagriculture:item/mystical_seeds"
    }
}
```

The following, almost identical, file works correctly, and is in fact the only working file:
```json
{
    "name": "Adamantite",
    "type": "mysticalagriculture:resource",
    "tier": "mysticalagradditions:6",
    "ingredient": {
        "item": "enlightened_end:adamantite_ingot"
    },
    "color": "4b7dfc",
    "textures": {
        "flower": "mysticalagriculture:block/flower_ingot",
        "essence": "mysticalagriculture:item/essence_ingot",
        "seeds": "mysticalagriculture:item/mystical_seeds"
    }
}
```

**Expected behavior**
The seeds to be created and have a recipe.

**Screenshots / Scripts / Logs**
Logs can be provided on request but I don't believe contain relevant info.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.3.5
 - Cucumber: 6.0.10
 - Mystical Agriculture: 6.0.13
 - Mystical Customization: 4.0.1
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
Logs would probably be useful. I just copied the Rich Slag seeds into a testing modpack I have and they seem to have worked fine, so maybe there's a specific seed that's causing issues?

![image](https://github.com/BlakeBr0/MysticalCustomization/assets/12994882/6118c98a-88e5-4bcc-9314-a0de417747f7)

**Comment by CraftSpider** [comment]
Sorry for the delay - I'll try removing them one by one next time I'm working on the pack. Aside from that, here's a log from a recent startup:

[latest.log](https://github.com/BlakeBr0/MysticalCustomization/files/14351953/latest.log)

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
