### ISSUE TITLE
Server Issue with custom seeds/crops.

### ISSUE THREAD

**Issue by Xephiro9999** [BlakeBr0/MysticalCustomization#48]
**Describe the bug**
Server doesn't start thanks to custom crops.
**To Reproduce**
Run arclight on 1.20.1 Version, have the mods and config.

**Expected behavior**
The server to start.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
Debug and logs, and Config from the server.
[debug.log](https://github.com/BlakeBr0/MysticalCustomization/files/15444477/debug.log)
[latest.log](https://github.com/BlakeBr0/MysticalCustomization/files/15444478/latest.log)
[mysticalcustomization.zip](https://github.com/BlakeBr0/MysticalCustomization/files/15444483/mysticalcustomization.zip)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: 7.0.8
 - Mystical Agriculture: 7.0.11
 - Mystical Customization: 5.0.1
 - Singleplayer or Multiplayer: Multiplayer, running Arclight

**Comment by BlakeBr0** [comment]
You'll have to disable the automatic recipe generation for your crops [(docs)](https://blakesmods.com/docs/mysticalcustomization/adding-crops#recipe-config) and add them yourself since the custom server you're using is changing Minecraft internals which breaks the dynamic recipe generation.

**Comment by BlakeBr0** [comment]
If you try with Cucumber version 7.0.10 does this issue still occur?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
