### ISSUE TITLE
essence to items?

### ISSUE THREAD

**Issue by demonjacobs666** [BlakeBr0/MysticalCustomization#5]
i managed to get the thing installed and new seeds made, but the essences don't become anything. is there a recipe template?

**Comment by ghost** [comment]
i have the same problem too. Can anybody help?

**Comment by ghost** [comment]
I now solved the Problem with Minetweaker.
1. installed Minetweaker Mod
2. created Folder "scripts"
3. created a ".zs" file inside that folder (name doesn't matter) with the following Code:

craftingTable.addShaped("shaped_example_1", <item:mysticalagriculture:prosperity_shard> * 6, [
    [<item:mysticalagriculture:prosperity_essence>, <item:mysticalagriculture:prosperity_essence>, <item:mysticalagriculture:prosperity_essence>],
    [<item:mysticalagriculture:prosperity_essence>, <item:minecraft:air>, <item:mysticalagriculture:prosperity_essence>],
    [<item:mysticalagriculture:prosperity_essence>, <item:mysticalagriculture:prosperity_essence>, <item:mysticalagriculture:prosperity_essence>]
]);

Like that i created a Crafting Recipe for Prosperity Shards with Prosperity Essence

**Comment by BlakeBr0** [comment]
The intention is to create your own recipes using a datapack or other means.
