### ISSUE TITLE
No secondary seed and essence drops for customized crops.

### ISSUE THREAD

**Issue by RTesseract** [BlakeBr0/MysticalCustomization#50]
**Describe the bug**
I defined a new crop Insanium seeds whose recipes and drops are both Insanium essence in Mystical Agradditions.
When harvesting, the crop always drops one Insanium essence and one Insanium seeds only. No extra essences and seeds.

**To Reproduce**
Create a new file called `insanium.json` and move it to the folder `mysticalcustomization/crops`.
File contents are as follows:
```json
{
    "name": "Insanium",
    "type": "resource",
    "tier": "mysticalagradditions:6",
    "ingredient": {
        "item": "mysticalagradditions:insanium_essence"
    },
    "color": "7400b8",
    "textures": {
        "flower": "mysticalagriculture:block/flower_dust",
        "essence": "mysticalagriculture:block/essence_dust"
    },
    "essence": "mysticalagradditions:insanium_essence",
    "baseSecondaryChance": 0.1,
    "respectsEffectiveFarmland": true
}
```
Open a world in Minecraft.
Get the seed `mysticalagriculture:insanium_seeds` (crop id: `mysticalcustomization:insanium`) and plant it on the Insanium farmland (from Mystical Agradditions mod).
Harvest it by left-clicking the crop.

**Expected behavior**
Each harvest should have a 20% chance of extra drops on Insanium farmland.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.3.13
 - Cucumber: 6.0.10
 - Mystical Agriculture: 6.0.14
 - Mystical Agradditions: 6.0.4
 - Mystical Customization: 4.0.1
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
So the `mysticalagradditions:6` tier explicitly disables secondary seed drops. If you edit it and set `secondarySeedDrop` to `true` it should work.

Alternatively you can create a new crop tier with your preferred attributes.

**Comment by RTesseract** [comment]
It works. Thank you :)
