### ISSUE TITLE
can't get the crop to drop the proper item

### ISSUE THREAD

**Issue by shadowslayer2081** [BlakeBr0/MysticalCustomization#52]
trying to get a custom crop to drop prosperity shards and i can't quite figure it out no matter what i add or change it either drops essence or doesn't show up at all

my current version of code is as follow:

{
  "name": "Prosperity",
  "type": "mysticalagriculture:prosperity_shard",
  "tier": "mysticalagriculture:1",
  "ingredient": {
    "item": "mysticalagriculture:prosperity_block"
  },
  "color": "D3E9EC",
  "textures": {
    "flower": "mysticalagriculture:block/flower_dust",
    "essence": "mysticalagriculture:item/essence_gem"
  },
  "crux": "mysticalagriculture:prosperity_block"
  {
  "essence": "mysticalagriculture:prosperity_shard"
}

 - Minecraft: 1.20.1
 - Forge:47.1.99
 - Cucumber: 7.0.9
 - Mystical Agriculture: 7.0.11
 - Mystical Customization: 5.0.1
 - Singleplayer or Multiplayer: singleplayer

**Comment by BlakeBr0** [comment]
That JSON is not valid (test with [this tool](https://jsonlint.com/)). Also `type` is supposed to be a crop type which should be one of the values outputted by the `/mysticalcustomization types` command. You probably want `mysticalagriculture:resource`.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
