### ISSUE TITLE
Seed recipes not changing, when using mystical customization (1.21.1)

### ISSUE THREAD

**Issue by FocusedVex** [BlakeBr0/MysticalCustomization#53]
I am currently in the process of opening a minecraft server on 1.21.1 NeoForge, at version 21.1.61.

When attempting to update the crafting recipes of the seeds and the tiers, I have so far been unsuccesful. I am using Visual Studio Code to do this and can't see any issues with the code and have also tried to just copy the code I had used on my 1.20 server, which also isn't working.

Im unsure if this is some form of bug or possibly a mod conflict, any help would be appreciated.

Code being used to change the tier crafting item:

`{
    "mysticalagriculture:elemental": {
      "essence": "mysticalagriculture:inferium_block"
    }
}`

Code being used to change the individual seed:

`{
    "mysticalagriculture:coal": {
      "ingredient": {
        "item": "minecraft:coal_block"
      }
    }
}`

These are just the start but would be extended to cover a number of seeds and all tiers, once I've managed to get it fixed.

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.61
 - Cucumber: 8.0.6
 - Mystical Agriculture: 8.0.7
 - Mystical Customization: 6.0.0
 - Singleplayer or Multiplayer: Currently Single Player but will be changed to a Server once working.

**Comment by BlakeBr0** [comment]
Are there any errors in the logs? I just tested locally and these changes seem to work when placed in `configure-tiers.json` and `configure-crops.json` respectively.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
