### ISSUE TITLE
Custom crop growth is not affected by Squat Grow mod

### ISSUE THREAD

**Issue by helmutfork** [BlakeBr0/MysticalCustomization#54]
**Describe the bug**
I have created a custom crop.  I can plant it harvest it, and the recipes for the essence I get are functioning.  I can accelerate the growth using the Mystical Agriculture fertilizer, but the growth is not affected by the Squat Grow mod.  All other Mystical Agriculture crops grow just fine using Squat Grow.

**To Reproduce**
Plant custom seed along side other Mystical Agriculture seeds.  Squat.  Watch all other seeds grow except for custom seed.

**Expected behavior**
I expect the custom seed to also grow.

**Screenshots / Scripts / Logs**
Not sure what scripts are needed...  No errors being generated in logs.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.0
 - Cucumber: 7.0.12
 - Mystical Agriculture: 7.0.14
 - Mystical Customization: 5.0.2
 - Singleplayer or Multiplayer: Both, same result.

**Comment by BlakeBr0** [comment]
Not sure how that mod works but the crops added by this mod are added in the exact same way as the base mod. Maybe that mod is based on block ids or tags? The crops added using Customization won't have any tags by default.

**Comment by helmutfork** [comment]
It appears that is the case, that it relies on tags.  What is the easiest way to add item tags to a new crop?  Would this be done through the json file used to create the recipe?

**Comment by BlakeBr0** [comment]
You can add tags using a normal datapack. I don't think there's a way for me to make it easier in this case due to the nature of tags.

**Comment by helmutfork** [comment]
I'll give it a try.  Thank you for your feedback!
