### ISSUE TITLE
Can't add Crop 1.16.5

### ISSUE THREAD

**Issue by Oatise** [BlakeBr0/MysticalCustomization#55]
**Describe the bug**
Can't add crop

**Expected behavior**
make seed/essence

**Screenshots / Scripts / Logs**
![image](https://github.com/user-attachments/assets/752156ab-621d-4dfa-8a21-b25236f28b4d)
![image](https://github.com/user-attachments/assets/5ae5cec8-6219-4db1-93ff-de1a363498c4)
![image](https://github.com/user-attachments/assets/0168b2e8-5e4e-4dbc-8dd1-7f47b2872ade)

*** I did as well make the color all lowercase but no luck either

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6
 - Mystical Customization: 2.1.7
 - Singleplayer or Multiplayer: Single

**Comment by BlakeBr0** [comment]
For the color, remove the `#` as that wasn't being automatically removed in the 1.16 version. 

As for the first error, there is no crop with id `mysticalagriculture:salt` in the base mod.

**Comment by Oatise** [comment]
Hi, is that not how I'm supposed to add crops? I know it's not an ID but I wanted to make a custom seed for the modpack

**Comment by BlakeBr0** [comment]
The second screenshot is an error from the `configure-crops.json` file which is for changing existing crops. The file from the first screenshot will be the new crop you're adding so you don't need to do anything in `configure-crops.json` in that case.

**Comment by Oatise** [comment]
I haven't done anything In the configure-crops.json I am putting it in the crops folder where the doc said to add new crops?

**Comment by BlakeBr0** [comment]
The second screenshot shows there's an error in the configure-crops.json file, which was what I was referring to. Did removing the # from the color code fix that issue for you?

**Comment by Oatise** [comment]
I actually cant get to my computer at all currently, out of town. I can try in the morning and reply asap

**Comment by FullMetalMaster** [comment]
Oat if you figure it out hit me up because I'm also trying to add crops

**Comment by Oatise** [comment]
Hello, Sorry for late response. Family issues came up. Removing that # fixed all of it. I thought I did something like that but must've not. Thank you very much.
