### ISSUE TITLE
Component Boimes doesnt't work in 1.20.1 with custom seeds

### ISSUE THREAD

**Issue by Hibizea1** [BlakeBr0/MysticalCustomization#56]
**Describe the bug**
I wan't to create a custom that can grow only in one biome, but he say Invalid Biome but i'm in the right biome.

**To Reproduce**
Create a new seeds,
Configure JSON,
in Biomes parameter put a biome (Vanilla biome or Custom biome)
restart Pack 
And he says Invalid Biome

**Expected behavior**
I wan't to grow a seeds in ad_astra:kunar_wastelands biome.

**Screenshots / Scripts / Logs**
![2024-12-27_11 30 45](https://github.com/user-attachments/assets/ffe04b14-b83b-47c5-b914-c881c4056c75)
![2024-12-27_11 31 15](https://github.com/user-attachments/assets/5cae0329-740a-4841-8717-981afb451765)

Config/mysticalcustomization/crops/desh_seed.json
{
  "name": "Desh Seed",
  "type": "mysticalagriculture:resource",
  "tier": "mysticalcustomization:7",
  "ingredient":{
    "item": "ad_astra:desh_ingot"
  },
  "color": "D86601",
  "textures": {
    "flower": "mysticalagriculture:block/flower_ingot",
    "essence": "mysticalagriculture:item/essence_ingot",
    "seeds": "mysticalagriculture:item/mystical_seeds"
  },
  "biomes": [
    "minecraft:plains"
  ]
}

[2024-12-27-7.log.gz](https://github.com/user-attachments/files/18259675/2024-12-27-7.log.gz)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.0
 - Cucumber: 7.0.13
 - Mystical Agriculture: 7.0.14
 - Mystical Customization: 5.0.2
 - Singleplayer or Multiplayer: singleplayer

**Comment by BlakeBr0** [comment]
Fixed in versions 7.0.15 and and 6.0.16 of Mystical Agriculture.
