### ISSUE TITLE
problem don't understand how to add seeds by mod

### ISSUE THREAD

**Issue by mobby45** [BlakeBr0/MysticalCustomization#7]
hello, i don't understand how to add a seed in game i made all he says on wiki nothing on game can you help me ?

**Comment by mobby45** [comment]
i want to add uraninite seed, uraninite become to mod powah

**Comment by BlakeBr0** [comment]
You can learn how to use this mod by reading the documentation here:
https://mods.blakebr0.com/docs/mysticalcustomization
